### PR TITLE
Log and EnvVar cleanup

### PR DESCRIPTION
**Pull request by Daytona675x**
Yo Seb! Trying to figure out how this stuff works. Looks as if I can only create a pull request which contains ALL the garba... errm valuable changes I made so far. And to make things worse, it apparently also includes stuff I included from you (although the last one wasnt done manually, so maybe git would get it right). Anyway, maybe you find it useful as is, otherwise dismiss :)

### CODE REVIEW

**Comment by ptitSeb** [comment]
Wow, there are a lot of stuff. I need to analyze a bit, and I'll merge it!

**Comment by Daytona675x** [comment]
Yeah, sorry :P Such sort of (even slight) refactoring easily results in many changes. At the end it's mostly sort of cosmetic stuff (which I think cant hurt though).

**Comment by ptitSeb** [comment]
You even thought of Android.mk, nice!

**Comment by Daytona675x** [comment]
;) A brave man you are!

**Comment by ptitSeb** [comment]
^^

I noticed that `initialize_gles()` had lost it's `constructor` attribute (it was the `static int inited` that got it...). So I fixed that, but I don't know if it can brake something or not on amiga / minigl side.

**Comment by Daytona675x** [comment]
Oh yes, nice catch!! Well, in my shared lib case it doesn't matter, but in a sobj case it surely does... Damn gcc... An error / warning would have been nice... Isnt this defined only for functions?!

**Comment by ptitSeb** [comment]
> Isnt this defined only for functions?!

Yes it is. I had a warning on my side (plus no env var was working).

**Pull request merged**
