### PR TITLE
Refactor: preload most function addresses

### PR DESCRIPTION
**Pull request by Mathias-Boulay**
Hi there, this PR is related to #440.
I wouldn't qualify it as ready, since some error logging as disappeared, but it is functional for android.

This is more like a showcase of progress to get some feedback on how things could be handled better

### CODE REVIEW

**Comment by ptitSeb** [comment]
Nice. That looks interesting.
I think host.h and host.c would benefit from some macro magic, to ease the process of maintenance. I'll try to find some time to contribute there.

The missing error logging are the "not found" function at load I assume?

**Comment by Mathias-Boulay** [comment]
Yes, there is no logging of the not found part.
I'll try to create macros to make it easier

**Comment by ptitSeb** [comment]
I was thinking of something like that: 
[macros.zip](https://github.com/ptitSeb/gl4es/files/12497928/macros.zip)

**Comment by Mathias-Boulay** [comment]
oh you commented right before I force pushed something. Let me look at it.

In the meantime, I guess you can take a new look at the host.c/h files, I used macros and integrated null detection

**Comment by Mathias-Boulay** [comment]
oh yeah you centralised it via `ALL_FUNCTIONS` then changed how it got replaced through other intermediate macros that have a different value depending on the file. Smart !

By the way, any specific reason behind starting your macros with `GO_` ?

**Comment by ptitSeb** [comment]
> oh yeah you centralised it via `ALL_FUNCTIONS` then changed how it got replaced through other intermediate macros that have a different value depending on the file. Smart !
> 
> By the way, any specific reason behind starting your macros with `GO_` ?

Why GO_? I don't know. Because it's rather short, and have no specific meany appart from "just do it"... On my other box86/box64 projects, there are many GO() macros, and some `SUPER()` also (instead of `ALL_FUNCTIONS()` here)... You could say it's a lack of imagination for good macros names I suppose.

**Comment by Mathias-Boulay** [comment]
Oh :sweat_smile: 
I'm modifying the code to add a more centralised macro like yours. Also, chances are you do not handle declaration of functions only loaded via OES or EXT extensions. I'll take this into account as well

**Comment by ptitSeb** [comment]
> Oh 😅 I'm modifying the code to add a more centralised macro like yours. Also, chances are you do not handle declaration of functions only loaded via OES or EXT extensions. I'll take this into account as well

Yeah, I agree, it seems something is missing about the OES and EXT extension...

**Comment by Mathias-Boulay** [comment]
Okay, new force push, more macros. I still didn't use macro for the fixed egl function but you can see the approach

**Comment by Mathias-Boulay** [comment]
> Yeah, I see. Looks good yes.
> 
> Is suppose OES and EXT macro is missing for now, as it's an empty one in `host.c`

It is empty on purpose, since OES and EXT still have to be loaded on the fly the first time through `eglProcAddress`. Therefore it should not generate code on the `host.c` side

**Comment by Mathias-Boulay** [comment]
One new force push, and I'm pretty sure that I am done

**Comment by ptitSeb** [comment]
I'll test to check how it behave on some exotic platform, like the Pyra.

**Comment by ptitSeb** [comment]
The `host.c` is missing from the `src/CMakeList.txt` file also

**Comment by Mathias-Boulay** [comment]
The initial goal of the PR is to present an example of the refactor for the codebase itself, and does not consider other build systems. Mostly because I'm not very familiar with them.

**Comment by Mathias-Boulay** [comment]
Taking a shot at loading functions early with `eglProcAddress` again, it seems to boot with `LIGL_ES=1`. iirc last time I failed to use the proper tests due to when the load was actually done.

**Comment by Mathias-Boulay** [comment]
I'll push a new attempt. Perhaps you know how to accurately test if the loading works as intended

**Comment by Mathias-Boulay** [comment]
For fun I pushed the early load further, by loading all LOAD_EGL functions early as well

**Comment by ptitSeb** [comment]
I'll merge this in a new branch, so I can fix the loading on other platforms.

**Comment by ptitSeb** [comment]
> For fun, in a local commit, I pushed the early load further, by loading all LOAD_EGL functions early as well. Minecraft still boots for now, although I don't think it uses many ogl states, if multiple at all..

I don't think there is much to gain with preloading the egl functions. There are rarely used, and with the preload of the gl functions, they will be called only on very rare occasions anyway (like, creating a new context, wich is slow anyway).

**Comment by Mathias-Boulay** [comment]
I guess at most you save on startup performance by potentially preloading egl functions

**Comment by Mathias-Boulay** [comment]
But at this point, it starts being negligible anyway

**Pull request merged**
