### PR TITLE
[GLES3] Add simple wrapper for glVertexAttribIPointer()

### PR DESCRIPTION
**Pull request by CosineMath**

### CODE REVIEW

**Comment by ptitSeb** [comment]
Mmmm, I don't like adding wrappers without emulation fallback. I merge it, but this really need some more work.
Also, this is OpenGL 3.x feature, wich gl4es doesn't support yet.

**Comment by khanhduytran0** [comment]
Wait, `glVertexAttribIPointer` can be wrapped to `glVertexAttribPointer`, which is a GLES2 function.

**Comment by ptitSeb** [comment]
Maybe, with disabling Normalization. But some changes in the shaders will be needed anyway. Which this PM don't handle at all.

**Comment by CosineMath** [comment]
Emm, so what are wrappers *with* emulation fallback?

**Comment by ptitSeb** [comment]
Well, in that case, using `glVertexAttirbPointer` if `glVertexAttribIPointer` is not available.
So that also mean checking if this function is available. And because it's only availbale when using GLES 3.x context and gl4es, for now, doesn't create or handle GLES 3.x context, it should never be available.

**Comment by CosineMath** [comment]
Sorry... I don't know details of GL4ES much. I am working on an experimental shader converter. I tested GL4ES with the converter on *desktop X11* and then found `glVertexAttirbPointer` missing. So I try to add a wrapper.

**Comment by ptitSeb** [comment]
Well, this function is only used with OpenGL 3.x shaders. Conversion to either GLES 3.x or GLES2.0 would be welcome.

**Pull request merged**
