### PR TITLE
Emscripten fixes

### PR DESCRIPTION
**Pull request by parasti**
Just some fixes for latest SDK.

I have been trying to get Neverball working on Emscripten. With gl4es, finally, it works! This is the only library that I found that implements all the needed fixed-function stuff AND works with Emscripten. There are no graphical glitches at all. Thanks!

### CODE REVIEW

**Comment by ptitSeb** [comment]
Neverball in web page ? That's great !

**Comment by ptitSeb** [comment]
Did you put a website with it?

**Comment by parasti** [comment]
Not yet, only just got it working! I will let you know when I do.

**Comment by parasti** [comment]
@ptitSeb Just to let you know, I created a demo site at https://parasti.github.io/

Here's my PR for Neverball, if you're interested: https://github.com/Neverball/neverball/pull/199

There were some issues with reflections/the stencil buffer, so for now I have turned off reflections. You can turn them back on in the Options screen, and observe the resulting glitches. :) I have not investigated this yet (will do), so can't say if this is due to GL4ES, SDL2 or Emscripten.

I would still be stuck in Emscripten legacy GL land if not for GL4ES, so thanks again!

**Comment by ptitSeb** [comment]
Yhanks for the info. That's nice ! It works well.

About the reflexion, what's wrong on your side? I activated them and, in the main menu at least, I saw nothing wrong:
image
You have something different or is only visible on some specific levels?

**Comment by parasti** [comment]
I didn't check on Chrome yet, but on Firefox the yellow goal halo extends below the floor (which shouldn't happen because it should be clipped by the stencil). It is clearly visible when entering the title screen.

**Comment by parasti** [comment]
@ptitSeb Good news: It's not a gl4es problem.

**Comment by ptitSeb** [comment]
Ah good :)
Thanks for the info, and for your PRs!

**Pull request merged**
