### PR TITLE
Fix crash on unload with NO_INIT_CONSTRUCTOR

### PR DESCRIPTION
**Pull request by lewa-j**
Better solution to https://github.com/FWGS/xash3d-fwgs/pull/255

### CODE REVIEW

**Comment by seisdr** [comment]
why the hell you use gl4es in xash3d

**Comment by lewa-j** [comment]
> 
> 
> why the hell you use gl4es in xash3d

Ask @mittorn

**Comment by mittorn** [comment]
Why not? It is able to run XashXT on GLES2

**Comment by seisdr** [comment]
it's full of graphical bugs

**Comment by ptitSeb** [comment]
> it's full of graphical bugs

If you are no happy with gl4es, don't use it. 
Just a reminder: this is gl4es github.

**Comment by w123456w30w** [comment]
> it's full of graphical bugs

Talk is cheap. Show me the code.

**Pull request merged**
